# This pre-commit config is mainly aimed at formatting and linting the Python files in python-objectstore-client.
# However, pre-commit requires this file to be placed at the root of the repository.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check --fix
        language: system
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types_or: [python, pyi]
      - id: mypy
        name: mypy
        entry: .venv/bin/mypy
        language: system
        types: [python]
