changelogPolicy: auto

targets:
  - name: github
  - name: crates
  - name: pypi
  - name: sentry-pypi
    internalPypiRepo: getsentry/pypi

requireNames:
  - /.*objectstore_client.*whl$/
  - /.*objectstore_client.*tar\.gz$/
