//! Error types for service and backend operations.
//!
//! [`Error`] covers I/O, serialization, HTTP, metadata, authentication,
//! and backend-specific failures. [`Result`] is the corresponding alias.

// Needed as the `.kind()` methods generated by `derive(ErrorKind)` currently lack documentation.
#![allow(missing_docs)]

use std::any::Any;
use std::borrow::Cow;
use std::fmt;

use objectstore_log::Level;
use reqwest::StatusCode;
use thiserror::Error as ThisError;

use crate::stream::{self, ClientStreamError};

/// The category of a service error.
///
/// These kinds describe the *cause* of a failure, independent of any HTTP
/// semantics. It is up to the API layer to decide how to map each kind onto a
/// status code, and which kinds to group together.
///
/// Users should rely on the kind for classification and handling, rather than matching on
/// specific variants.
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum ErrorKind {
    /// Error originating from a client-supplied request body stream.
    ClientStream,
    /// Malformed client input (bad metadata, JSON, upload id, …).
    InvalidInput,
    /// The requested byte range is not satisfiable for the object's size.
    RangeNotSatisfiable,
    /// This service instance has reached its own concurrency limit and is
    /// shedding load.
    AtCapacity,
    /// A storage backend rejected the operation with a rate-limit response.
    BackendRateLimited,
    /// A storage backend timed out.
    BackendTimeout,
    /// A storage backend is temporarily unavailable.
    BackendUnavailable,
    /// Operation unsupported by this service instance.
    NotImplemented,
    /// Internal failure.
    Internal,
}

/// Structured error detail parsed from a backend HTTP error response.
///
/// Formats conditionally: includes only the fields that are non-empty.
#[derive(Debug)]
pub struct BackendDetail {
    /// Machine-readable error code (e.g., "InvalidArgument", "NoSuchKey").
    pub code: String,
    /// Human-readable error message from the response body.
    pub message: String,
}

impl BackendDetail {
    /// Creates a new [`BackendDetail`] with empty code and message.
    pub fn none() -> Self {
        Self {
            code: String::new(),
            message: String::new(),
        }
    }
}

impl fmt::Display for BackendDetail {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match (self.code.is_empty(), self.message.is_empty()) {
            (false, false) => write!(f, "{} (backend code {})", self.message, self.code),
            (true, false) => write!(f, "{}", self.message),
            (false, true) => write!(f, "backend code {}", self.code),
            (true, true) => Ok(()),
        }
    }
}

/// Error type for service operations.
#[derive(Debug, ThisError, derive_error_kind::ErrorKind)]
#[error_kind(ErrorKind)]
pub enum Error {
    /// IO errors related to payload streaming or file operations.
    #[error("i/o error: {0}")]
    #[error_kind(ErrorKind, Internal)]
    Io(std::io::Error),

    /// Error originating from a client-supplied input stream.
    #[error("error reading client stream: {0}")]
    #[error_kind(ErrorKind, ClientStream)]
    ClientStream(#[from] ClientStreamError),

    /// Errors related to de/serialization.
    #[error(transparent)]
    #[error_kind(transparent)]
    Serde(#[from] SerdeError),

    /// Errors from storage backend HTTP calls, transport-level or application-level.
    #[error(transparent)]
    #[error_kind(transparent)]
    Backend(#[from] BackendError),

    /// Errors related to de/serialization and parsing of object metadata.
    #[error(transparent)]
    #[error_kind(transparent)]
    Metadata(#[from] MetadataError),

    /// Errors encountered when attempting to authenticate with GCP.
    #[error("GCP authentication error: {0}")]
    #[error_kind(ErrorKind, Internal)]
    GcpAuth(#[from] gcp_auth::Error),

    /// A spawned service task panicked.
    #[error("service task failed: {0}")]
    #[error_kind(ErrorKind, Internal)]
    Panic(String),

    /// A spawned service task was dropped before it could deliver its result.
    ///
    /// This is an unexpected condition that can occur when the runtime drops the task for unknown
    /// reasons.
    #[error("task dropped")]
    #[error_kind(ErrorKind, Internal)]
    Dropped,

    /// A redirect tombstone was encountered at a place where it is not supported.
    ///
    /// This indicates a caller bug — tombstone-aware reads must go through the
    /// [`HighVolumeBackend`](crate::backend::common::HighVolumeBackend) methods.
    #[error("unexpected tombstone")]
    #[error_kind(ErrorKind, Internal)]
    UnexpectedTombstone,

    /// The requested byte range is not satisfiable for the object's size.
    #[error("range not satisfiable (object size: {total} bytes)")]
    #[error_kind(ErrorKind, RangeNotSatisfiable)]
    RangeNotSatisfiable {
        /// Total size of the object in bytes.
        total: u64,
    },

    /// The service has reached its concurrency limit and cannot accept more operations.
    #[error("concurrency limit reached")]
    #[error_kind(ErrorKind, AtCapacity)]
    AtCapacity,

    /// Any other error stemming from one of the storage backends, which might be specific to that
    /// backend or to a certain operation.
    #[error("storage backend error: {context}")]
    #[error_kind(ErrorKind, Internal)]
    Generic {
        /// Context describing the operation that failed.
        context: String,
        /// The underlying error, if available.
        #[source]
        cause: Option<Box<dyn std::error::Error + Send + Sync>>,
    },

    /// The functionality is not implemented by this instance of the service.
    #[error("not implemented")]
    #[error_kind(ErrorKind, NotImplemented)]
    NotImplemented,

    /// Invalid upload ID for a multipart upload.
    #[error(transparent)]
    #[error_kind(ErrorKind, InvalidInput)]
    InvalidUploadId(#[from] objectstore_types::multipart::InvalidUploadId),
}

impl Error {
    /// Creates an [`Error::Panic`] from a panic payload, extracting the message.
    pub fn panic(payload: Box<dyn Any + Send>) -> Self {
        let msg = if let Some(s) = payload.downcast_ref::<&str>() {
            (*s).to_owned()
        } else if let Some(s) = payload.downcast_ref::<String>() {
            s.clone()
        } else {
            "unknown panic".to_owned()
        };
        Self::Panic(msg)
    }

    /// Creates an [`Error`] from a reqwest error with context, categorizing it by status code or
    /// transport-level failure signal.
    pub fn reqwest(context: impl Into<Cow<'static, str>>, cause: reqwest::Error) -> Self {
        if let Some(client_error) = stream::unpack_client_error(&cause) {
            return Self::ClientStream(client_error);
        }

        Self::Backend(BackendError::from_reqwest(context, cause))
    }

    /// Creates an [`Error::Serde`] from a serde error with context, categorizing it as an internal
    /// error.
    pub fn serde(context: impl Into<Cow<'static, str>>, cause: serde_json::Error) -> Self {
        Self::Serde(SerdeError {
            kind: ErrorKind::Internal,
            context: context.into(),
            cause,
        })
    }

    /// Creates an [`Error::Serde`] from a serde error with context, categorizing it as a client
    /// error.
    pub fn serde_client(context: impl Into<Cow<'static, str>>, cause: serde_json::Error) -> Self {
        Self::Serde(SerdeError {
            kind: ErrorKind::InvalidInput,
            context: context.into(),
            cause,
        })
    }

    /// Creates an [`Error::Metadata`] from a metadata error with context, categorizing it as an
    /// internal error.
    pub fn metadata(
        context: impl Into<Cow<'static, str>>,
        cause: objectstore_types::metadata::Error,
    ) -> Self {
        Self::Metadata(MetadataError {
            kind: ErrorKind::Internal,
            context: context.into(),
            cause,
        })
    }

    /// Creates an [`Error::Metadata`] from a metadata error with context, categorizing it as a
    /// client error.
    pub fn metadata_client(
        context: impl Into<Cow<'static, str>>,
        cause: objectstore_types::metadata::Error,
    ) -> Self {
        Self::Metadata(MetadataError {
            kind: ErrorKind::InvalidInput,
            context: context.into(),
            cause,
        })
    }

    /// Creates an [`Error::Generic`] with a context string and no cause.
    pub fn generic(context: impl Into<String>) -> Self {
        Self::Generic {
            context: context.into(),
            cause: None,
        }
    }

    /// Returns the appropriate log level for this error.
    pub fn level(&self) -> Level {
        match self.kind() {
            ErrorKind::ClientStream | ErrorKind::InvalidInput | ErrorKind::RangeNotSatisfiable => {
                Level::DEBUG
            }
            ErrorKind::AtCapacity
            | ErrorKind::BackendRateLimited
            | ErrorKind::BackendTimeout
            | ErrorKind::BackendUnavailable => Level::WARN,
            ErrorKind::NotImplemented | ErrorKind::Internal => Level::ERROR,
        }
    }
}

impl From<std::io::Error> for Error {
    fn from(cause: std::io::Error) -> Self {
        match stream::unpack_client_error(&cause) {
            Some(client_error) => Self::ClientStream(client_error),
            None => Self::Io(cause),
        }
    }
}

/// A backend HTTP or transport-level error.
///
/// Unifies transport-level failures (no response received, e.g. connection reset or timeout) and
/// HTTP error responses (4xx/5xx), with or without a structured error body, under a single kind
/// classification.
#[derive(Debug)]
pub struct BackendError {
    kind: ErrorKind,
    context: Cow<'static, str>,
    status: Option<StatusCode>,
    detail: BackendDetail,
    cause: Option<reqwest::Error>,
}

impl BackendError {
    /// Creates a [`BackendError`] for an HTTP error response, categorizing it by status code.
    pub(crate) fn from_status(
        context: impl Into<Cow<'static, str>>,
        status: StatusCode,
        detail: BackendDetail,
    ) -> Self {
        Self {
            kind: kind_for_status(status),
            context: context.into(),
            status: Some(status),
            detail,
            cause: None,
        }
    }

    /// Creates a [`BackendError`] from a reqwest error, categorizing it by status code if the
    /// error carries one, or by transport-level failure signal otherwise.
    fn from_reqwest(context: impl Into<Cow<'static, str>>, cause: reqwest::Error) -> Self {
        let status = cause.status();
        let kind = match status {
            Some(status) => kind_for_status(status),
            None if cause.is_timeout() => ErrorKind::BackendTimeout,
            None if cause.is_connect() || cause.is_request() => ErrorKind::BackendUnavailable,
            None => ErrorKind::Internal,
        };

        Self {
            kind,
            context: context.into(),
            status,
            detail: BackendDetail::none(),
            cause: Some(cause),
        }
    }

    /// Returns the service-level category for this backend error.
    pub fn kind(&self) -> ErrorKind {
        self.kind
    }

    /// Returns the HTTP status code, if a response was received.
    pub fn status(&self) -> Option<StatusCode> {
        self.status
    }

    /// Returns the parsed error code and message from the response body, if any.
    pub fn detail(&self) -> &BackendDetail {
        &self.detail
    }

    /// Returns the underlying reqwest error, if this is a transport-level failure.
    pub fn cause(&self) -> Option<&reqwest::Error> {
        self.cause.as_ref()
    }
}

impl fmt::Display for BackendError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.context)?;
        if let Some(status) = self.status {
            write!(f, " ({status})")?;
        }
        if !self.detail.code.is_empty() || !self.detail.message.is_empty() {
            write!(f, ". {}", self.detail)?;
        }
        Ok(())
    }
}

impl std::error::Error for BackendError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.cause
            .as_ref()
            .map(|e| e as &(dyn std::error::Error + 'static))
    }
}

/// Maps an HTTP status code from a storage backend to a service-level [`ErrorKind`].
fn kind_for_status(status: StatusCode) -> ErrorKind {
    match status {
        StatusCode::TOO_MANY_REQUESTS => ErrorKind::BackendRateLimited,
        StatusCode::REQUEST_TIMEOUT | StatusCode::GATEWAY_TIMEOUT => ErrorKind::BackendTimeout,
        StatusCode::INTERNAL_SERVER_ERROR
        | StatusCode::BAD_GATEWAY
        | StatusCode::SERVICE_UNAVAILABLE => ErrorKind::BackendUnavailable,
        status if status.is_client_error() => ErrorKind::InvalidInput,
        _ => ErrorKind::Internal,
    }
}

/// Serde error with context and kind.
#[derive(Debug, ThisError)]
#[error("serde error: {context}")]
pub struct SerdeError {
    kind: ErrorKind,
    context: Cow<'static, str>,
    #[source]
    cause: serde_json::Error,
}

impl SerdeError {
    /// Returns the service-level category for this serde error.
    pub fn kind(&self) -> ErrorKind {
        self.kind
    }

    /// Returns the underlying serde error.
    pub fn cause(&self) -> &serde_json::Error {
        &self.cause
    }
}

/// Metadata error with context and kind.
#[derive(Debug, ThisError)]
#[error("metadata error: {context}")]
pub struct MetadataError {
    kind: ErrorKind,
    context: Cow<'static, str>,
    #[source]
    cause: objectstore_types::metadata::Error,
}

impl MetadataError {
    /// Returns the service-level category for this metadata error.
    pub fn kind(&self) -> ErrorKind {
        self.kind
    }

    /// Returns the underlying metadata error.
    pub fn cause(&self) -> &objectstore_types::metadata::Error {
        &self.cause
    }
}

/// Result type for service operations.
pub type Result<T, E = Error> = std::result::Result<T, E>;
