//! Error types for service and backend operations.
//!
//! [`Error`] covers I/O, serialization, HTTP, metadata, authentication,
//! and backend-specific failures. [`Result`] is the corresponding alias.

// Needed as the `.kind()` methods generated by `derive(ErrorKind)` currently lack documentation.
#![allow(missing_docs)]

use std::any::Any;
use std::borrow::Cow;

use objectstore_log::Level;
use reqwest::StatusCode;
use thiserror::Error as ThisError;

use crate::stream::{self, ClientStreamError};

/// The category of a service error.
///
/// Users should rely on the kind for classification and handling, rather than matching on
/// specific variants.
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum ErrorKind {
    /// Error originating from a client-supplied request body stream.
    ClientStream,
    /// Transient failure that may succeed if retried.
    Transient,
    /// Malformed client input.
    BadRequest,
    /// Operation unsupported by this service instance.
    NotImplemented,
    /// Service or upstream capacity limit.
    TooManyRequests,
    /// Internal failure.
    Internal,
}

/// Error type for service operations.
#[derive(Debug, ThisError, derive_error_kind::ErrorKind)]
#[error_kind(ErrorKind)]
pub enum Error {
    /// IO errors related to payload streaming or file operations.
    #[error("i/o error: {0}")]
    #[error_kind(ErrorKind, Internal)]
    Io(std::io::Error),

    /// Error originating from a client-supplied input stream.
    #[error("error reading client stream: {0}")]
    #[error_kind(ErrorKind, ClientStream)]
    ClientStream(#[from] ClientStreamError),

    /// Errors related to de/serialization.
    #[error(transparent)]
    #[error_kind(transparent)]
    Serde(#[from] SerdeError),

    /// Reqwest errors from storage backend HTTP calls.
    #[error(transparent)]
    #[error_kind(transparent)]
    Reqwest(#[from] ReqwestError),

    /// Errors related to de/serialization and parsing of object metadata.
    #[error(transparent)]
    #[error_kind(transparent)]
    Metadata(#[from] MetadataError),

    /// Errors encountered when attempting to authenticate with GCP.
    #[error("GCP authentication error: {0}")]
    #[error_kind(ErrorKind, Internal)]
    GcpAuth(#[from] gcp_auth::Error),

    /// A spawned service task panicked.
    #[error("service task failed: {0}")]
    #[error_kind(ErrorKind, Internal)]
    Panic(String),

    /// A spawned service task was dropped before it could deliver its result.
    ///
    /// This is an unexpected condition that can occur when the runtime drops the task for unknown
    /// reasons.
    #[error("task dropped")]
    #[error_kind(ErrorKind, Internal)]
    Dropped,

    /// A redirect tombstone was encountered at a place where it is not supported.
    ///
    /// This indicates a caller bug — tombstone-aware reads must go through the
    /// [`HighVolumeBackend`](crate::backend::common::HighVolumeBackend) methods.
    #[error("unexpected tombstone")]
    #[error_kind(ErrorKind, Internal)]
    UnexpectedTombstone,

    /// The requested byte range is not satisfiable for the object's size.
    #[error("range not satisfiable (object size: {total} bytes)")]
    #[error_kind(ErrorKind, BadRequest)]
    RangeNotSatisfiable {
        /// Total size of the object in bytes.
        total: u64,
    },

    /// The service has reached its concurrency limit and cannot accept more operations.
    #[error("concurrency limit reached")]
    #[error_kind(ErrorKind, TooManyRequests)]
    AtCapacity,

    /// Any other error stemming from one of the storage backends, which might be specific to that
    /// backend or to a certain operation.
    #[error("storage backend error: {context}")]
    #[error_kind(ErrorKind, Internal)]
    Generic {
        /// Context describing the operation that failed.
        context: String,
        /// The underlying error, if available.
        #[source]
        cause: Option<Box<dyn std::error::Error + Send + Sync>>,
    },

    /// The functionality is not implemented by this instance of the service.
    #[error("not implemented")]
    #[error_kind(ErrorKind, NotImplemented)]
    NotImplemented,

    /// Invalid upload ID for a multipart upload.
    #[error(transparent)]
    #[error_kind(ErrorKind, BadRequest)]
    InvalidUploadId(#[from] objectstore_types::multipart::InvalidUploadId),
}

impl Error {
    /// Creates an [`Error::Panic`] from a panic payload, extracting the message.
    pub fn panic(payload: Box<dyn Any + Send>) -> Self {
        let msg = if let Some(s) = payload.downcast_ref::<&str>() {
            (*s).to_owned()
        } else if let Some(s) = payload.downcast_ref::<String>() {
            s.clone()
        } else {
            "unknown panic".to_owned()
        };
        Self::Panic(msg)
    }

    /// Creates an [`Error`] from a reqwest error with context, classifying it as an internal
    /// error.
    pub fn reqwest(context: impl Into<Cow<'static, str>>, cause: reqwest::Error) -> Self {
        if let Some(client_error) = stream::unpack_client_error(&cause) {
            return Self::ClientStream(client_error);
        }

        Self::Reqwest(ReqwestError::internal(context, cause))
    }

    /// Creates an [`Error`] from a reqwest error, classifying it according to its status code.
    pub fn reqwest_transparent(
        context: impl Into<Cow<'static, str>>,
        cause: reqwest::Error,
    ) -> Self {
        if let Some(client_error) = stream::unpack_client_error(&cause) {
            return Self::ClientStream(client_error);
        }

        Self::Reqwest(ReqwestError::transparent(context, cause))
    }

    /// Creates an [`Error::Serde`] from a serde error with context, classifying it as an internal
    /// error.
    pub fn serde(context: impl Into<Cow<'static, str>>, cause: serde_json::Error) -> Self {
        Self::Serde(SerdeError {
            kind: ErrorKind::Internal,
            context: context.into(),
            cause,
        })
    }

    /// Creates an [`Error::Serde`] from a serde error with context, classifying it as a client
    /// error.
    pub fn serde_client(context: impl Into<Cow<'static, str>>, cause: serde_json::Error) -> Self {
        Self::Serde(SerdeError {
            kind: ErrorKind::BadRequest,
            context: context.into(),
            cause,
        })
    }

    /// Creates an [`Error::Metadata`] from a metadata error with context, classifying it as an
    /// internal error.
    pub fn metadata(
        context: impl Into<Cow<'static, str>>,
        cause: objectstore_types::metadata::Error,
    ) -> Self {
        Self::Metadata(MetadataError {
            kind: ErrorKind::Internal,
            context: context.into(),
            cause,
        })
    }

    /// Creates an [`Error::Metadata`] from a metadata error with context, classifying it as a
    /// client error.
    pub fn metadata_client(
        context: impl Into<Cow<'static, str>>,
        cause: objectstore_types::metadata::Error,
    ) -> Self {
        Self::Metadata(MetadataError {
            kind: ErrorKind::BadRequest,
            context: context.into(),
            cause,
        })
    }

    /// Creates an [`Error::Generic`] with a context string and no cause.
    pub fn generic(context: impl Into<String>) -> Self {
        Self::Generic {
            context: context.into(),
            cause: None,
        }
    }

    /// Returns the appropriate log level for this error.
    pub fn level(&self) -> Level {
        match self.kind() {
            ErrorKind::ClientStream | ErrorKind::BadRequest => Level::DEBUG,
            ErrorKind::Transient | ErrorKind::TooManyRequests => Level::WARN,
            ErrorKind::NotImplemented | ErrorKind::Internal => Level::ERROR,
        }
    }
}

impl From<std::io::Error> for Error {
    fn from(cause: std::io::Error) -> Self {
        match stream::unpack_client_error(&cause) {
            Some(client_error) => Self::ClientStream(client_error),
            None => Self::Io(cause),
        }
    }
}

/// Reqwest error with context and kind.
#[derive(Debug, ThisError)]
#[error("reqwest error: {context}")]
pub struct ReqwestError {
    kind: ErrorKind,
    context: Cow<'static, str>,
    #[source]
    cause: reqwest::Error,
}

impl ReqwestError {
    fn internal(context: impl Into<Cow<'static, str>>, cause: reqwest::Error) -> Self {
        Self {
            kind: ErrorKind::Internal,
            context: context.into(),
            cause,
        }
    }

    fn transparent(context: impl Into<Cow<'static, str>>, cause: reqwest::Error) -> Self {
        let kind = if let Some(status) = cause.status() {
            match status {
                StatusCode::TOO_MANY_REQUESTS => ErrorKind::TooManyRequests,
                StatusCode::REQUEST_TIMEOUT
                | StatusCode::INTERNAL_SERVER_ERROR
                | StatusCode::BAD_GATEWAY
                | StatusCode::SERVICE_UNAVAILABLE
                | StatusCode::GATEWAY_TIMEOUT => ErrorKind::Transient,
                status if status.is_client_error() => ErrorKind::BadRequest,
                _ => ErrorKind::Internal,
            }
        } else if cause.is_timeout() || cause.is_connect() || cause.is_request() {
            ErrorKind::Transient
        } else {
            ErrorKind::Internal
        };

        Self {
            kind,
            context: context.into(),
            cause,
        }
    }

    /// Returns the service-level category for this reqwest error.
    pub fn kind(&self) -> ErrorKind {
        self.kind
    }

    /// Returns the underlying reqwest error.
    pub fn cause(&self) -> &reqwest::Error {
        &self.cause
    }
}

/// Serde error with context and kind.
#[derive(Debug, ThisError)]
#[error("serde error: {context}")]
pub struct SerdeError {
    kind: ErrorKind,
    context: Cow<'static, str>,
    #[source]
    cause: serde_json::Error,
}

impl SerdeError {
    /// Returns the service-level category for this serde error.
    pub fn kind(&self) -> ErrorKind {
        self.kind
    }

    /// Returns the underlying serde error.
    pub fn cause(&self) -> &serde_json::Error {
        &self.cause
    }
}

/// Metadata error with context and kind.
#[derive(Debug, ThisError)]
#[error("metadata error: {context}")]
pub struct MetadataError {
    kind: ErrorKind,
    context: Cow<'static, str>,
    #[source]
    cause: objectstore_types::metadata::Error,
}

impl MetadataError {
    /// Returns the service-level category for this metadata error.
    pub fn kind(&self) -> ErrorKind {
        self.kind
    }

    /// Returns the underlying metadata error.
    pub fn cause(&self) -> &objectstore_types::metadata::Error {
        &self.cause
    }
}

/// Result type for service operations.
pub type Result<T, E = Error> = std::result::Result<T, E>;
