//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "part")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub part_size: i32,
    pub compression: Compression,
    pub compressed_size: i32,
    pub segment_id: Uuid,
    pub segment_offset: i32,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "i16", db_type = "SmallUnsigned")]
pub enum Compression {
    #[sea_orm(num_value = 0)]
    None,
    #[sea_orm(num_value = 1)]
    Zstd,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
