# Ignored by docker compose, used by devservices
x-sentry-service-config:
  version: 0.1
  service_name: objectstore
  dependencies:
    objectstore:
      description: Objectstore server
    bigtable:
      description: Google Cloud BigTable emulator
    gcs:
      description: Google Cloud Storage emulator
    minio:
      description: MinIO server
  modes:
    default: []
    containerized: [objectstore]
    full: [bigtable, gcs, minio]

x-programs:
  devserver:
    command: cargo run --

services:
  objectstore:
    image: ghcr.io/getsentry/objectstore:nightly
    environment:
      OS__STORAGE__TYPE: "filesystem"
      OS__STORAGE__PATH: "/data"
      OS__LOGGING__LEVEL: "debug"
      OS__AUTH__ENFORCE: "false"
    command: run
    healthcheck:
      test: ["CMD", "/bin/entrypoint", "healthcheck"]
      interval: 5s
      timeout: 1s
      retries: 5
    ports:
      - 127.0.0.1:8888:8888
    volumes:
      - objectstore-data:/data
    networks:
      - devservices
    labels:
      - orchestrator=devservices
    restart: unless-stopped
  bigtable:
    image: google/cloud-sdk
    command: /run-bigtable.sh
    environment:
      BIGTABLE_EMULATOR_HOST: localhost:8086
    healthcheck:
      test: cbt -project testing -instance objectstore count objectstore
      interval: 5s
      timeout: 1s
      retries: 5
    ports:
      - 127.0.0.1:8086:8086
    volumes:
      - ./run-bigtable.sh:/run-bigtable.sh
    networks:
      - devservices
    labels:
      - orchestrator=devservices
    restart: unless-stopped
  gcs:
    build: https://github.com/getsentry/google-cloud-storage-testbench.git#main
    environment:
      GOOGLE_CLOUD_CPP_STORAGE_TEST_BUCKET_NAME: test-bucket
    healthcheck:
      test: curl -f http://localhost:9000
      interval: 5s
      timeout: 1s
      retries: 5
    ports:
      - 127.0.0.1:8087:9000
    networks:
      - devservices
    labels:
      - orchestrator=devservices
    restart: unless-stopped
  minio:
    image: minio/minio
    entrypoint: /run-minio.sh
    healthcheck:
      test: mc ready local
      interval: 5s
      timeout: 1s
      retries: 5
    ports:
      - 127.0.0.1:8089:9000
    volumes:
      - ./run-minio.sh:/run-minio.sh
    networks:
      - devservices
    labels:
      - orchestrator=devservices
    restart: unless-stopped

networks:
  devservices:
    name: devservices
    external: true

volumes:
  objectstore-data:
