name: Validate sentry-options schema

on:
  pull_request:
    paths:
      - 'sentry-options/schemas/**'

permissions:
  contents: read

jobs:
  validate:
    uses: getsentry/sentry-options/.github/workflows/validate-schema.yml@5ae5958b3c4bf104efc46d61e9d155f45cefe1d8 # TODO: Replace!
    secrets:
      SENTRY_INTERNAL_APP_PRIVATE_KEY: ${{ secrets.SENTRY_INTERNAL_APP_PRIVATE_KEY }}
    with:
      schemas-path: sentry-options/schemas
