remote: http://localhost:18888

duration: 5s

workloads:
  - name: attachments
    mode: throughput
    organizations: 1000
    file_sizes:
      p50: 50 KiB
      p99: 200 KiB
    actions:
      writes: 10
      reads: 0
      deletes: 0
  - name: profiling
    concurrency: 8
    file_sizes:
      p50: 15 KiB
      p99: 100 KiB
  - name: replays
    concurrency: 16
    file_sizes:
      p50: 25 KiB
      p99: 400 KiB
  - name: nodestore
    concurrency: 32
    file_sizes:
      p50: 5 KiB
      p99: 20 KiB
