remote: http://localhost:8888

duration: 10s

workloads:
  - name: snapshots
    mode: batch
    concurrency: 1
    file_sizes:
      p50: 5 KiB
      p99: 20 KiB
    actions:
      writes: 20000
      reads: 0
      deletes: 0
